- README.md
Here's a "one pager" as discussed in yesterday's meeting, with the goal of having some basic content in place before LPC 2022.
> Initial content for mptcp.dev

- details.md
- faq.md
Better to move all the questions here on the website, than having some there, and some here.
I adapted some of the answers. You can find the original ones [here](https://github.com/multipath-tcp/mptcp_net-next/wiki/Home/_compare/34ba2883e2a30b15a149df94a941b446eb51e1d6...6a6efb312538dc83534e09a76c1cbd90f7dfaa9a)
> faq: add some questions and answers from the wiki

- index.md
It looks like the 'index' page was missing titles and a section about use-cases (suggested on Fediverse).
> index: add missing titles and use cases

- README.md
- contributing.md
It looks like it was missing.
I initially started a page on our wiki [1], but it looks like this should be on the website.
Link: https://github.com/multipath-tcp/mptcp_net-next/wiki/Contributing [1]
> contributing: how people can help

- mptcp-info.md
When calling getsockopt(MPTCP_INFO), MPTCP_INFO_FLAG_FALLBACK will never be set. Instead the syscall will return an error, for both the client and the server side.
MPTCP_INFO_FLAG_FALLBACK will only be set when listing MPTCP connections via the Netlink API (hence the confusion).
We can simplify the examples now:
- getsockopt(MPTCP_INFO) for both the client and server, kernels >= 5.16
- getsockopt(SO_PROTOCOL) for the server only, only check the client request, kernels < 5.16
> info: fallback: MPTCP_INFO_FLAG_FALLBACK is never set

- faq.md
Instead of using multipath-tcp.org which might be confusing with the fork, and on port 5000, not HTTPS: now using https://check.mptcp.dev
Some more info will be added on this page: link, the curl cmd with mptcpize, test files to download
> faq: check server: new URL

- faq.md
A few modifications here:
- Add a link to Apple's 'network' page for the documentation in C language, not just for Objective C and Swift.
- Removed `disconnectx()`: there is no mention of multipath support.
- Mention `AF_MULTIPATH` [1], that appears to be needed before using `connectx()`.
- Mention that it is not recommended (even if it appears to work for the moment, only one subflow is used [2]).
Link: https://github.com/search?q=repo%3Aapple-oss-distributions%2Fxnu+PF_MULTIPATH&type=code [1]
Link: https://github.com/matttbe/curl/pull/1 [2]
> faq: clarify macOS support

- contributing.md
It is good to say that there are ways to contribute, but no references were used to help readers to know where to go to contribute in one way or another, even if they are mentioned somewhere on the website.
Reported-by: Igu and Maja from APC.org.
> contributing: add missing refs

- setup.md
It sounds interesting to add more details about each limit: for who (client/server), and the default value.
While at it, use a list.
(Note that I did two small modifications before that: f3adc6b2807b9bc424c06b8de906c48c6e2bd848 & aa8e152a5fe3b5490edfd24445c5654e1d7107dd ; I don't think they needed to be reviewed)
EDIT: + two other improvements
> setup: limits: for who and defaults

- _config.yml
It was not referenced anywhere on the website.
> config: nav: link to MPTCP sysctl doc

- pm.md
Because it can help people deploying MPTCP behind a load balancer.
Also mention that it is linked to 'ndiffports', the name used in the fork kernel.
> pm: describe the 'port' option

- apps.md
Hello. This patch adds v2ray-core to the list of apps that support MPTCP. The documentation link does not document MPTCP yet. The patch to document it was submitted. https://github.com/v2fly/v2fly-github-io/pull/462
> apps: add v2ray-core

- apps.md
OpenWRT's future version (v24?) will support MPTCP by default on non "small flash" targets. No need for custom builds or forks!
Thanks to @dangowrt, @rodsmar, and @sKyissKy for the work, and @hauke for the review!
Link: https://github.com/openwrt/openwrt/pull/16786
> apps: add OpenWRT support

- apps.md
OpenWrt is spelled 'OpenWrt' and not 'OpenWRT'. Fix that.
> apps: fix OpenWrt spelling

- apps.md
As pointed out by arinc9 and dangowrt [[1]](https://github.com/multipath-tcp/mptcp.dev/pull/26), it would be clearer to have a dedicated Linux distributions sections, because OpenWrt is not an application.
Here I tried to list most common GNU/Linux distributions, avoiding forks having the same kernel configuration and mptcpd package. Raspbian and Ubuntu have different kernel configurations and are quite popular, it is better to mention them.
I decided to add a new section in the 'apps' page, not to create yet another page, while it is linked to the rest.
Because it is better not to rename a page to avoid breaking links, I changed the title instead: Support in apps / OS. It covers what is currently in this page, and still linked to 'apps'.
> apps: add 'Linux distributions' section

- mptcp-info.md
For most cases, it might be enough to only use `TCP_IS_MPTCP`: either it is supported, and we can check if a fallback happened by looking at the value filled by the kernel, or we can check `errno`: `ENOPROTOOPT` means it is not an MPTCP socket: the client didn't request to use MPTCP.
If really needed, the workaround is to use `MPTCP_INFO` like it was presented before, only for >= 5.16 kernels.
(+ a few clean-ups)
> mptcp info: recommend using `TCP_IS_MPTCP`

- apps.md
I don't think mptcpd is packaged: these OS are mainly to execute containers.
For Amazon, it looks like MPTCP is available according to this issue containing a full dmesg log where we can see MPTCP token hash table has been initialised:
https://github.com/amazonlinux/amazon-linux-2023/issues/696
> os: add Amazon & Azure Linux

- pm.md
Here are some small improvements for the PM page:
- reduce title levels
- how to display endpoints and limits
- add a reminder that `ADD_ADDR` are typically for the server side
- add a reminder that that automated tools create `sublow` endpoints by default, not `signal` ones.
> pm: various small improvements.

- faq.md
Because OpenSSH maintainers do not want to add a native MPTCP support, it is not that obvious what to do to enable this support: on the server side, the socket might be created by systemd, while on the client side, GUI might use SSH, but they are not launched from a terminal.
A few different cases are now covered here.
Because the list is a bit long, it will not be displayed by default, a '(click to see more)' label will be visible instead.
> faq: enable MPTCP support with OpenSSH

- pm.md
It doesn't support MPTCP yet.
Because it is installed in some embedded environments by default, it sounds good to mention that the "full" version is needed, e.g. ip-full in OpenWRT.
> pm: note about Busybox's ip command

- apps.md
It has been recently accepted in 'edge/community' repo, so it should be available in the next stable version, expected around May 2025.
> apps: Alpine: mptcpd should be in 3.22

- pm.md
The 'subflow' endpoint description might be confusing: is it needed to be specified to create subflows to additional IP announced by the other peer. Mentioning that it is only to create subflows to the other peer's IP address should help clarifying this.
Link: https://github.com/multipath-tcp/mptcp_net-next/issues/554
> pm: subflow: specify the destination IP

- faq.md
Two small precisions:
- mention `ssh.socket` restart: Even if that makes sense after the modification, it is better to be explicit.
- proxy is an alternative: Clearly mention that the `ProxyCommand` is an alternative, less efficient than using SSH with MPTCP support directly. Also mention that other commands like scp, rsync, git, etc. can be used with `mptcpize run` as well.
> faq: ssh: more precisions

- apps.md
Two popular HTTP Go apps. Caddy recently switched to Go 1.24 and has MPTCP support enabled by default.
> apps: add Caddy and Traefik

- faq.md
At Netdev 0x19, there were some discussions about hardware GRO: Eric reported that when comparing performances of TCP with MPTCP single-path, a performance drop can be explained by hardware GRO not being used with MPTCP.
Apparently, some NIC's skip hardware GRO in presence of "unknown" TCP options: anything but TCP timestamps. At least that what people who worked on Intel NIC's said. (I hope that's OK to mention Intel here, that's apparently specific to them, but I don't know more about that.)
It then seems interesting to write this down in the FAQ to help people understanding why hardware GRO might not be used with MPTCP. While at it, explain that software GRO works when TSO was used on the sender side.
> faq: add GRO support info

- README.md
- load-balancer.md
Deploying MPTCP on the server side is very easy. It is a bit more complex when it is deployed behind a stateless L4 load balancer.
Add a new dedicated page that would help people having such infrastructure, e.g. CDNs.
Do not hesitate to add any suggestions that would be useful to these people (or others to make sure this setup is only needed for specific cases).
Note: you can show the mermaid graphs by clicking on the "Display the rich diff" button, or click on "View file", or check on [mermaid.live](https://mermaid.live/edit#pako:eNqNkM1uwjAQhF_F2lMrBRonQMAqHKCXSjk1t9Y9mHgJEY6NjNM_lHevIYVWCFB92l3PfDvaLeRGIjBYKPOeL4V1JH3imvg3u-GwEGwhOpWZlwrv55bcTWaqRO043JJOhzzq0pVCkU093_n9aELS6fbgy5WpZWtLjZBkKpTQOVoOzc8KMh6TDHOj5ZExHu8Y7X86JZ2uZ2b05cDcoH1D20KzfU0oh9df_flUWXSNEP0lnI-URSeR4mvAeA9sHarUq8x9KiQ …
> Deployments behind a load-balancer
