- index.md
All emails in HTML will be ignored, including the ones to subscribe. Add a note about that.
Also mention we are supposed to get a challenge.
Otherwise, people don't know what to expect, and might think they have been subscribed while they didn't.
Reported-by: @gdetal
> ml: plain text only

- apps.md
Not released yet, but accepted, and queued for the next version.
> apps: add cURL and SystemD

- README.md
- contributing.md
- debugging.md
- details.md
- faq.md
- implementation.md
- index.md
- mptcp-info.md
- pm.md
- setup.md
Please note that this PR depends on #11. (that's why the base is not `main`).
A new PM page, with a new "Behavior" section (and some small changes)
> New dedicated PM page, with a new "Behavior" section

- pm.md
It sounds better to be more explicit about that: the page here only described the main options, not everything in details as it is presented in the man page.
> pm: check the man page for more details

- apps.md
VLC will support MPTCP starting from version 4.0
> Add VLC in apps

- apps.md
If everything goes well, it should be available as part of the future v2.5.1 version.
Thanks to @Aperence for the work, and @notroj and @ylavic for the helpful reviews!
> apps: add Apache support

- apps.md
Thanks to @mozillazg for the work!
> apps: add pTCPDump support

- _includes/head_custom.html
It is supposed to add a mention to this account when sharing links on the Fediverse.
> head: add fediverse creator metadata

- pm.md
It is important to know that, not to have NM and mptcpd configuring the endpoints. Also, in most cases, it might not be needed to configure these endpoints if NM or mptcpd does the job for the user.
While at it, mention that the in-kernel PM is the default one, and add a note about `rp_filter`, the same as the one mentioned in NM's release notes.
Link: https://networkmanager.dev/blog/networkmanager-1-40/#mptcp-support
> pm: NM >= 1.40 set the endpoints by default

- faq.md
Just two simple fixes, see the individual commits.
> faq: fix link in summary + mention all OSes

- apps.md
Thanks @Aperence for the initial work.
> apps: iOS: add Nextcloud

- apps.md
Enabled since v133.
Thanks @Aperence for the work.
> apps: ios: add Firefox

- apps.md
The -rc4 has been recently published.
> apps: os: OpenWrt support from 24.10

- apps.md
Needed to manually configure MPTCP endpoints and limits.
> apps: os: openwrt: mention 'ip-full'

- apps.md
Thanks to @pizhenwei for the dev work, and the Valkey maintainers for the reviews.
> apps: linux: add Valkey

- apps.md
Thanks to @fw-strlen for the dev work, and Pablo Neira Ayuso for the reviews.
> apps: linux: add NFTables

- apps.md
Asked by @geliangtang.
Link: https://lore.kernel.org/b14a64255536ee68225ea4142e26c40b9869e811.camel@kernel.org
> apps: os: Kylin OS

- load-balancer.md
The performance impact is something that often worry system administrators.
> lb: note about the perf impact

- apps.md
Thanks to @pizhenwei for the dev work, and the Valkey maintainers for the reviews.
https://github.com/valkey-io/valkey/pull/1961
> apps: linux: Valkey: add replica option

- apps.md
Thanks to Maxim Dounin (@mdounin from freenginx), Maxime Dourov (@mux99), and Anthony Doeraene (@Aperence).
It looks like I missed the good news :)
> apps: linux: add freenginx

- apps.md
Thanks to Maxim Dounin (freenginx), Maxime Dourov (@mux99), and Anthony Doeraene (@Aperence).
The patch was taken from freenginx apparently.
> apps: linux: add Angie
